apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
commonAnnotations:
  grafana_folder: "TKE"

configMapGenerator:
  - files:
      - tke-workload-on-super-node.json
    name: dashboard-tke-workload-on-super-node
  - files:
      - tke-pvc.json
    name: dashboard-tke-pvc
  - files:
      - tke-node.json
    name: dashboard-tke-node
  - files:
      - tke-pod.json
    name: dashboard-tke-pod
  - files:
      - tke-super-node.json
    name: dashboard-tke-super-node
  - files:
      - tke-pod-on-node.json
    name: dashboard-tke-pod-on-node
  - files:
      - tke-cluster.json
    name: dashboard-tke-cluster
