{
 "title": "集群概览",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up{}, cluster)" } }
  ]
 },
 "panels": [
  { "title": "Pod 统计", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "集群 Pod 规模",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{cluster=\"$cluster\"}) by (phase)",
     "legendFormat": "{{phase}}"
    }
   ]
  },
  { "title": "调度", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU 分配率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"cpu\"}) by (node)\n/\non (node) group_left kube_node_status_allocatable{cluster=\"$cluster\", resource=\"cpu\", node!~\"eklet.*\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "内存分配率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=\"$cluster\", resource=\"memory\"}) by (node)\n/\non (node) group_left kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\", node!~\"eklet-.*\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod 数量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{cluster=\"$cluster\", node!~\"eklet-.*|\"}) by (node) ",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Pod 分配率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{cluster=\"$cluster\", phase=\"Running\"} * on (cluster, namespace, pod) group_left(node) kube_pod_info) by (node)\n/\non (node) group_left kube_node_status_allocatable{cluster=\"$cluster\", resource=\"pods\", node!~\"eklet-.*\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "计算",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 - avg(irate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"idle\"}[2m])) by (instance))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "内存使用率",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n1 - \n    (\n      node_memory_MemAvailable_bytes{cluster=\"$cluster\"} / \n      node_memory_MemTotal_bytes{cluster=\"$cluster\"}\n    )\n)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "进程数量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_procs_running{cluster=~\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "平均负载(1分钟)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "网络",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "出流量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_transmit_bytes_total{cluster=\"$cluster\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "入流量",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(irate(node_network_receive_bytes_total{cluster=\"$cluster\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TCP 连接数",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{cluster=\"$cluster\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "异常监控",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "NotReady 历史监控",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"Ready\", status=\"false\"} == 1",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "当前 Not Ready 的节点",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "kube_node_status_condition{condition=\"Ready\", status=\"false\"} == 1"
      }
     ]
    },
    {
     "title": "异常 Pod 统计",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "sum (kube_pod_status_reason{cluster=\"$cluster\"}) by (reason) > 0",
       "legendFormat": "{{phase}}"
      }
     ]
    },
    {
     "title": "CPU 限流",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total[$__rate_interval])) by (namespace, pod)",
       "legendFormat": "{{namespace}}/{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}