{
 "title": "路由器监控大盘",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "device",
    "label": "磁盘",
    "query": {
     "query": "label_values(node_filesystem_size_bytes{mountpoint!=\"/boot\", fstype!~\"nfs.*|tmpfs|ramfs|vfat\"},device)"
    }
   }
  ]
 },
 "panels": [
  { "title": "概览", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "使用率",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "CPU 使用率"
    },
    {
     "expr": "1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "1 - ( node_filesystem_avail_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"} )",
     "legendFormat": "磁盘空间使用率"
    },
    {
     "expr": "1 - ( node_filesystem_files_free{mountpoint=\"/\"} / node_filesystem_files{mountpoint=\"/\"} )",
     "legendFormat": "磁盘 inode 使用率"
    },
    {
     "expr": "avg by (instance)(node_load5) / count by (instance)(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "5分钟平均负载"
    }
   ]
  },
  {
   "title": "系统信息",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "uptime"
    },
    {
     "expr": "count by (instance) (node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "cpu"
    },
    { "expr": "node_memory_MemTotal_bytes", "legendFormat": "总内存" },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\"}",
     "legendFormat": "总容量"
    },
    {
     "expr": "avg by (instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})",
     "legendFormat": "temp"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "可用内存" },
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes - node_memory_MemFree_bytes - node_memory_SReclaimable_bytes",
     "legendFormat": "已用内存"
    },
    {
     "expr": "node_memory_Buffers_bytes + node_memory_Cached_bytes + node_memory_SReclaimable_bytes",
     "legendFormat": "buff/cache"
    },
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "空闲内存" },
    { "expr": "node_memory_Shmem_bytes", "legendFormat": "共享内存" }
   ]
  },
  {
   "title": "磁盘",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"}",
     "legendFormat": "总容量"
    },
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"}",
     "legendFormat": "剩余空间"
    },
    {
     "expr": "1 - ( node_filesystem_avail_bytes{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"} / node_filesystem_size_bytes{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"} )",
     "legendFormat": "空间使用率"
    },
    {
     "expr": "1 - ( node_filesystem_files_free{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"} / node_filesystem_files{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"} )",
     "legendFormat": "inode使用率"
    },
    {
     "expr": "node_filesystem_files{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"}",
     "legendFormat": "inode 总量"
    },
    {
     "expr": "node_filesystem_files_free{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"}",
     "legendFormat": "剩余 inode 数量"
    }
   ]
  },
  {
   "title": "温度",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by (sensor, instance) (node_hwmon_temp_celsius{chip=\"platform_coretemp_0\"})",
     "legendFormat": "传感器 {{sensor}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])))",
     "legendFormat": "使用率"
    },
    {
     "expr": "sum by (instance) (irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) ",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "内存",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes)",
     "legendFormat": "使用率"
    },
    {
     "expr": "node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes",
     "legendFormat": "使用量"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"} - node_filesystem_free_bytes{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"}) /\nnode_filesystem_size_bytes{fstype!~\"nfs.*|tmpfs|ramfs|vfat\", mountpoint!=\"/boot\"}",
     "legendFormat": "{{ mountpoint }}"
    }
   ]
  },
  {
   "title": "流量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_receive_bytes_total{device=\"ppp0\"}[$__rate_interval]))",
     "legendFormat": "入流量"
    },
    {
     "expr": "-sum(irate(node_network_transmit_bytes_total{device=\"ppp0\"}[$__rate_interval]))",
     "legendFormat": "出流量"
    }
   ]
  },
  {
   "title": "平均负载",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1min" },
    { "expr": "node_load5", "legendFormat": "5min" },
    { "expr": "node_load15", "legendFormat": "15min" },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"idle\"})",
     "legendFormat": "核数"
    }
   ]
  },
  {
   "title": "FD 数量",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "FD 数量" }
   ]
  },
  { "title": "CPU 明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "CPU 使用率(单核)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval])) by (cpu))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "CPU 使用率明细",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{mode!=\"idle\"}[$__rate_interval])) by (instance, mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  { "title": "磁盘明细", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "磁盘空间使用情况 - $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
   "repeat": "device",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{device=~\"$device\"} - node_filesystem_free_bytes{device=~\"$device\"}",
     "legendFormat": "磁盘使用量"
    },
    {
     "expr": "(node_filesystem_size_bytes{device=~\"$device\"} - node_filesystem_free_bytes{device=~\"$device\"}) /\nnode_filesystem_size_bytes{device=~\"$device\"}",
     "legendFormat": "磁盘使用率"
    }
   ]
  },
  {
   "title": "磁盘 inode 使用情况 - $device",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 69 },
   "repeat": "device",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_filesystem_files{device=~\"$device\"} - node_filesystem_files_free{device=~\"$device\"}",
     "legendFormat": "使用量"
    },
    {
     "expr": "(node_filesystem_files{device=~\"$device\"} - node_filesystem_files_free{device=~\"$device\"}) /\nnode_filesystem_files{device=~\"$device\"}",
     "legendFormat": "使用率"
    }
   ]
  },
  {
   "title": "磁盘 IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} 读流量"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} 写流量"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\"}[$__rate_interval])",
     "legendFormat": "{{device}} IO 时间"
    }
   ]
  },
  {
   "title": "磁盘 IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} 读 IOPS"
    },
    {
     "expr": "irate(node_disk_writes_completed_total[$__rate_interval])",
     "legendFormat": "{{device}} 写 IOPS"
    }
   ]
  },
  { "title": "Pod 监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 } },
  {
   "title": "CPU 使用量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod!=\"\"}[$__rate_interval])) by (namespace, pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "内存使用量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container!=\"\", pod!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "FD使用量",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_file_descriptors{pod!=\"\", container!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}